### ISSUE TITLE
希望日历能设置从周一或者周日作为第一天

### ISSUE THREAD

**Issue by sinnerliu** [GXFG/newtab-naivetab#21]
希望日历能设置从周一或者周日作为第一天，目前为周一为第一天，经常看错，😂

**Comment by GXFG** [comment]
感谢反馈，已记录在需求池内，会随着v1.7发布🤩

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sinnerliu ***@***.***>
发送时间: Monday, September 26, 2022 8:17:02 PM
收件人: GXFG/newtab-naivetab ***@***.***>
抄送: Subscribed ***@***.***>
主题: [GXFG/newtab-naivetab] 希望日历能设置从周一或者周日作为第一天 (Issue #21)


希望日历能设置从周一或者周日作为第一天，目前为周一为第一天，经常看错，😂

**Comment by GXFG** [comment]
V1.7.1已发布🤩
