### ISSUE TITLE
键盘书签在新标签页无法使用

### ISSUE THREAD

**Issue by fievell** [GXFG/newtab-naivetab#23]
问题描述：在新标签页无法使用键盘书签，按下指定键后无反应，只有开启全局快捷键后可以使用。已尝试chrome和edge的商店插件（1.6.5）和最新版（1.7.0），均无法在标签页使用键盘书签。后尝试关闭其他所有插件，仍无法解决。

插件版本：1.6.5和1.7.0
浏览器版本：Edge Version 105.0.1343.53 (Official build) (arm64)
系统：MacOS Monterey12.6

**Comment by GXFG** [comment]
请先检查以下两项：
1. 键盘书签设置->双击按键打开，是否为开启状态，开启状态下需要双击对应按键才可以完成打开书签
2. 新建标签页后，需要点击一下页面内任意元素，让页面处于获焦状态后才可以使快捷键生效
如以上操作仍未能解决您的问题的话，麻烦提供导出的设置json文件（注意隐藏好个人书签信息），这样可以更快的定位问题。
最后，感谢反馈：）

**Comment by fievell** [comment]
已尝试清除缓存，依然无法使用，且即使reset后也无法使用

**Comment by GXFG** [comment]
感谢反馈，已完成修复，V1.7.1正在审核，预计很快就可以发布成功了。

**Comment by fievell** [comment]
1.7.1 bug已修复，所有功能正常
(非常好的扩展，感谢您的付出)

**Comment by GXFG** [comment]
感谢您的喜欢🤩
