### ISSUE TITLE
V1.7.4根据分辨率调整尺寸，导致键盘显示的太小了，看不清楚了

### ISSUE THREAD

**Issue by sinnerliu** [GXFG/newtab-naivetab#27]
V1.7.4 优化：组件支持根据屏幕浏览器分辨率自动调整尺寸

更新后根据分辨率调整尺寸，导致键盘显示的太小了，看不清楚了，希望各个组件能自定义大小

**Comment by GXFG** [comment]
目前各个组件均支持自定义大小，键盘书签可通过调整对应设置面板“样式”下的“宽度”来实现自定义按键尺寸。
看通过如上操作是否能解决这个问题。: )

**Comment by sinnerliu** [comment]
好的，多谢提醒，可以满足
