### ISSUE TITLE
键盘配列同步不正确

### ISSUE THREAD

**Issue by FlynnWangNZ** [GXFG/newtab-naivetab#34]
我有两台电脑分别登录同一个谷歌账号, 设置键盘配列为33, 但是刷新后会变成61.
复现步骤:
1. A电脑设置键盘配列33, 刷新后不变.
2. B电脑启动浏览器, 默认为61, 修改设置为33, 刷新后不变.
3. A电脑刷新, 变成61
4. B电脑刷新, 也变成61

疑似是这个配置在同步的时候有冲突问题

**Comment by GXFG** [comment]
感谢反馈，我周六尝试复现一下。

**Comment by GXFG** [comment]
Hi，我测试了个人的两台Mac、一台Windows11电脑，发现这个case与个人电脑与Chrome同步的网络情况相关。
网络情况良好时：
1. A电脑设置键盘配列33, 刷新后不变；
2. B电脑启动浏览器，这里打开新页面键盘配列会同步成33；
在网络情况不稳定时，如果此刻操作修改了B电脑的设置，待网络情况稳定后，因B电脑的配置为最后修改的，会导致覆盖A电脑的配置。
目前综合来看，建议B电脑多等待几分钟待数据同步完成。后面我会看下这部分逻辑

> 我有两台电脑分别登录同一个谷歌账号, 设置键盘配列为33, 但是刷新后会变成61. 复现步骤:
> 
> 1. A电脑设置键盘配列33, 刷新后不变.
> 2. B电脑启动浏览器, 默认为61, 修改设置为33, 刷新后不变.
> 3. A电脑刷新, 变成61
> 4. B电脑刷新, 也变成61
> 
> 疑似是这个配置在同步的时候有冲突问题

Hi，我测试了个人的两台Mac、一台Windows11电脑，发现这个case与个人电脑与Chrome同步的网络情况相关。
网络情况良好时：
1. A电脑设置键盘配列33, 刷新后不变；
2. B电脑启动浏览器，这里打开新页面键盘配列会同步成33。

在网络情况不稳定时：
1. A电脑设置键盘配列33, 刷新后不变；
2.B电脑启动浏览器发现键盘配列没有同步为33，然后操作修改了键盘配列为61；
3. 待网络情况稳定后，因B电脑的配置为最后修改的，会导致同步成功后会覆盖A电脑的配置信息，两台电脑的键盘配列均为61。

目前综合来看，建议在网络情况不稳定时，B电脑多等待几分钟待数据同步完成。
后面我会看下是否有对应方案可以解决这个case，感谢反馈。

**Comment by FlynnWangNZ** [comment]
1.我在海外, 不存在网络问题.
2.不论等多久, 这个问题都会出现, 所以感觉也不是数据同步的问题.
我再描述一下我的现象:
1. A电脑设置为33. 此时A电脑无论刷新还是重新打开, 都是33, 没有问题.
2. B电脑打开主页, 就是默认的61, 不会同步为33(其他设置会同步, 只有键盘配列这个没有同步)
3. B电脑设置为33, 此时B电脑无论刷新还是重新打开, 都是33, 没有问题.
4. 但是此时A电脑刷新, 就会变成61.
不知道我有没有描述清楚问题现象.

**Comment by GXFG** [comment]
了解，

**Comment by GXFG** [comment]
> 1.我在海外, 不存在网络问题. 2.不论等多久, 这个问题都会出现, 所以感觉也不是数据同步的问题. 我再描述一下我的现象:
> 
> 1. A电脑设置为33. 此时A电脑无论刷新还是重新打开, 都是33, 没有问题.
> 2. B电脑打开主页, 就是默认的61, 不会同步为33(其他设置会同步, 只有键盘配列这个没有同步)
> 3. B电脑设置为33, 此时B电脑无论刷新还是重新打开, 都是33, 没有问题.
> 4. 但是此时A电脑刷新, 就会变成61.
>    不知道我有没有描述清楚问题现象.

感谢反馈，我会再多找几台电脑测试一下。

**Comment by GXFG** [comment]
Hi，可以尝试更新至V1.12.0，看是否能解决这个问题。
