### ISSUE TITLE
Vite server did not start

### ISSUE THREAD

**Issue by chestnutpro** [GXFG/newtab-naivetab#35]
Hello, I am trying to start the project myself, load extension, and the command used is
  `npm run dev` page display Vite Server did not start

**Comment by chestnutpro** [comment]
There is another question, I have always had this error when `run dev ` ,My version is the version of the main branch
![image](https://user-images.githubusercontent.com/115682103/220838024-2a74b675-9ae2-4664-abf8-f48318a080da.png)

**Comment by GXFG** [comment]
Hi，The current dev environment is still not working, please run 'npm run build' to build. Please refer to issue : https://github.com/antfu/vitesse-webext/issues/59 , and look forward to the official solution.

**Comment by chestnutpro** [comment]
thanks I don't pay attention to it
