### ISSUE TITLE
提议,能否加入一个英语词典,每次打开新标签页时自动刷新

### ISSUE THREAD

**Issue by Arose-z** [GXFG/newtab-naivetab#44]
如题

**Comment by GXFG** [comment]
能大致描述一下功能点和使用流程吗，只看标题的话不是很好对齐信息。不是很理解“打开新标签页时自动刷新英语词典”来完成什么。

**Comment by Arose-z** [comment]
具体功能点可以参考"Mainichi Tango",在每次打开新标签页时学习一个新的单词卡片.
