### ISSUE TITLE
keyboardType同步不正确

### ISSUE THREAD

**Issue by FlynnWangNZ** [GXFG/newtab-naivetab#55]
现象：PlugIn升级或其他情况丢失localStorage的时候， 从google同步之后， keyboardType会变成默认的61

复现：
1. 通用设置 -- 书签 -- 键盘配列， 修改为33（非默认的61）
2. 等待console log Upload config-bookmark complete
3. Application -- Storage -- Clear site data
4. refresh， 此时键盘配列会变成默认的61

分析：src -- logic -- storage.ts  `const mergeState` line 180~182
localStorage中存储的keyboardType是String类型， defaultConfig中是number类型， 此时直接返回默认值

建议：统一定义keyboardType为string类型(config.ts -- defaultConfig, keyboard.ts -- KEYBOARD_TYPE_CONFIG中的key )

Ps：我想提pr，但是不懂这个project怎么run，不会测试验证。

Pps：说了你可能不信， 我正在写issue，突然发现版本更新到了1.18.1，并且这个问题已经修复。
但问题是，github上并没有看到1.18.1的改动，也就是说Chrome插件市场里的版本，并不是从github出去的。
这可能是因为开发者需要及时修复bug提前走了发布流程，但这表明了一个隐患，即**我们使用的版本，并不是GitHub上的开源版本**，这一点有悖于项目宣称的**源码开源，无任何隐私信息或操作信息的获取，你的任何信息都是私有的**

**Comment by GXFG** [comment]
感谢反馈
1. keyboardType的同步问题是本周二完成修复并提交商店审核，Chrome web store今天审核通过自动发布的。
2. 请放心，商店发布的代码和Github上提交的是完全一致的，可以通过比对[extension.zip](https://github.com/GXFG/newtab-naivetab/blob/main/extension.zip)进行验证。只是因国内网络原因造成目前我个人的开发习惯是每个周末进行统一的代码提交。

**Comment by FlynnWangNZ** [comment]
感谢作者开源分享，没有恶意，个人非常喜欢这个项目，也一直在使用。希望这个项目越来越好。
