### ISSUE TITLE
背景图希望每天能自动更新

### ISSUE THREAD

**Issue by KleinPan** [GXFG/newtab-naivetab#6]
背景图希望每天能自动更新，而不是自动拉取微软的，放在网络分组下边，要手动点击才能替换

**Comment by GXFG** [comment]
Hi，感谢反馈。
下一个版本在背景图的来源选项里，增加了一项“每日一图”，选中后背景会自动切换至当天Bing的每日一图，预计1-2周后会发布。
不知道能否完全满足描述的这个场景。

**Comment by GXFG** [comment]
> 背景图希望每天能自动更新，而不是自动拉取微软的，放在网络分组下边，要手动点击才能替换

V1.0.0已发布

**Comment by KleinPan** [comment]
好的，感谢
