### ISSUE TITLE
今天最烦恼的事情是发现了naivetab，但是不支持firefox。

### ISSUE THREAD

**Issue by Zpipishrimp** [GXFG/newtab-naivetab#63]
最喜欢naivetab的新建标签页时自动聚焦搜索栏功能和书签键盘设计。
由于原生不支持firefox，我通过其他方式强行安装了naivetab，但可惜前端样式虽在，我喜欢的两个功能却并没有生效。。  
请求作者可以考虑下适配firefox。

**Comment by GXFG** [comment]
> 最喜欢naivetab的新建标签页时自动聚焦搜索栏功能和书签键盘设计。
> 由于原生不支持firefox，我通过其他方式强行安装了naivetab，但可惜前端样式虽在，我喜欢的两个功能却并没有生效。。  
> 请求作者可以考虑下适配firefox。

感谢对NaiveTab的喜欢，我会记录下适配Firefox这个功能点，但考虑到多支持一个浏览器对开发和测试确实有着不小的成本，所以是否会支持该功能以及完成的时间点目前还是不能确定的，后续我会评估一下。

**Comment by Zpipishrimp** [comment]
> > 最喜欢naivetab的新建标签页时自动聚焦搜索栏功能和书签键盘设计。
> > 由于原生不支持firefox，我通过其他方式强行安装了naivetab，但可惜前端样式虽在，我喜欢的两个功能却并没有生效。。
> > 请求作者可以考虑下适配firefox。
> 
> 感谢对NaiveTab的喜欢，我会记录下适配Firefox这个功能点，但考虑到多支持一个浏览器对开发和测试确实有着不小的成本，所以是否会支持该功能以及完成的时间点目前还是不能确定的，后续我会评估一下。

感谢您的回复，期待适配~

**Comment by GXFG** [comment]
已发布至Firefox，https://addons.mozilla.org/zh-CN/firefox/addon/naivetab-%E6%96%B0%E6%A0%87%E7%AD%BE%E9%A1%B5/
