### ISSUE TITLE
希望可以添加一言组件

### ISSUE THREAD

**Issue by iuuuuuuuu** [GXFG/newtab-naivetab#72]
希望可以添加可拓展的一言组件   填入api 选择 字段 比如说  一言 作者 来源 这些可以根据用户填入的字段 data[字段] 获取,可以增强拓展性,还可以配置字体大小等.... 会更加美观

**Comment by GXFG** [comment]
感谢反馈，这个想法听起来很棒，让我思考一下，后续的版本会考虑增加上的。
